Repository ssu-User-Interface/Booking, pull requests merged in 2024-12, with the labels that each got.

#87 [Feat/#85] mapbottomsheetfragment recyclerview
  app/src/main/java/com/example/booking/data/model/Book.java
  app/src/main/java/com/example/booking/presentation/map/BookItem.java
  app/src/main/java/com/example/booking/presentation/map/MapBottomSheetAdapter.java
  app/src/main/java/com/example/booking/presentation/map/MapBottomSheetDialogFragment.java
  app/src/main/java/com/example/booking/presentation/map/MapFragment.java
  app/src/main/java/com/example/booking/presentation/map/MapSearchFragment.java
  app/src/main/java/com/example/booking/presentation/registration/RecordRegistrationBottomSheetDialogFragment.java
  app/src/main/java/com/example/booking/presentation/registration/RecordRegistrationFragment.java
  app/src/main/java/com/example/booking/presentation/registration/RecordRegistrationViewModel.java
  app/src/main/res/layout/fragment_record_bottom_sheet.xml
  app/src/main/res/layout/fragment_record_registration.xml
Labels: :zap:Simba, FEAT

#88 Feat/#86 수민 파트 점검
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/java/com/example/booking/presentation/home/HomeFragment.java
  app/src/main/java/com/example/booking/presentation/record/RecordFragment.java
  app/src/main/java/com/example/booking/presentation/record/RecordSpecificFragment.java
  app/src/main/java/com/example/booking/presentation/record/RecordViewModel.java
  app/src/main/java/com/example/booking/presentation/record/adapter/RecordAdapter.java
  app/src/main/res/drawable/drawer_little_corenr_outline.xml
  app/src/main/res/drawable/ic_home_fisrt_widget.xml
  app/src/main/res/drawable/ic_home_fisrt_widget_right.xml
  app/src/main/res/drawable/ic_record_specific_star2.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_record_list_item.xml
  app/src/main/res/layout/fragment_record_specific.xml
  app/src/main/res/layout/fragment_timer.xml
  build.gradle.kts
Labels: :zap:Maro, FEAT, FIX

#91 [Feat/#89] page 를 위한 알라딘 api
  app/build.gradle.kts
  app/src/main/java/com/example/booking/datasource/AladinDataSource.java
  app/src/main/java/com/example/booking/datasourceImpl/AladinDataSourceImpl.java
  app/src/main/java/com/example/booking/di/AladinRetrofit.java
  app/src/main/java/com/example/booking/di/DataSourceModule.java
  app/src/main/java/com/example/booking/di/NaverRetrofit.java
  app/src/main/java/com/example/booking/di/NetworkModule.java
  app/src/main/java/com/example/booking/dto/response/BookSearchPageResponseDto.java
  app/src/main/java/com/example/booking/dto/response/BookSearchResponseDto.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchDetailFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchDetailViewModel.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchSaveBottomSheetFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchViewModel.java
  app/src/main/java/com/example/booking/repository/BookRepository.java
  app/src/main/java/com/example/booking/service/AladinApiService.java
  app/src/main/java/com/example/booking/service/AladinDetailApiService.java
  app/src/main/res/navigation/main_graph.xml
Labels: :zap: Kara, FEAT

#93 [FEAT/#92] 책 검색 필터링 기능 구현
  app/src/main/java/com/example/booking/datasource/NaverDataSource.java
  app/src/main/java/com/example/booking/datasourceImpl/NaverDataSourceImpl.java
  app/src/main/java/com/example/booking/presentation/home/HomeFragment.java
  app/src/main/java/com/example/booking/presentation/mypage/MyFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchViewModel.java
  app/src/main/java/com/example/booking/repository/BookRepository.java
  app/src/main/java/com/example/booking/service/NaverApiService.java
  app/src/main/res/layout/fragment_book_search.xml
  app/src/main/res/menu/book_search_filter_menu.xml
Labels: :zap: Kara, FEAT

#94 Fix/#90 map list click event error
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/booking/presentation/map/MapFragment.java
  app/src/main/java/com/example/booking/presentation/map/MapSearchFragment.java
  app/src/main/java/com/example/booking/presentation/record/RecordSpecificFragment.java
  app/src/main/java/com/example/booking/presentation/registration/PlaceSearchKeyword.java
  app/src/main/java/com/example/booking/presentation/registration/RecordRegistrationFragment.java
  app/src/main/res/drawable/ic_my_location.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_record_registration.xml
  app/src/main/res/navigation/main_graph.xml
Labels: :zap:Simba, FIX
