Repository ssu-User-Interface/Booking, pull requests merged in 2024-11, with the labels that each got.

#5 UI/#4 UI font 추가
  app/src/main/res/font/pretendard_black.otf
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_extrabold.otf
  app/src/main/res/font/pretendard_extralight.otf
  app/src/main/res/font/pretendard_light.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/font/pretendard_thin.otf
Labels: Maro, UI

#8 UI/#7상단 바 제작
  .github/ISSUE_TEMPLATE/issue-template.md
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_line_long.xml
  app/src/main/res/layout/fragment_top.xml
Labels: Simba, UI

#11 [UI/#9] 로그인 / 회원가입 / 홈 화면 구현
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/ic_home_book-playstore.png
  app/src/main/img_book-playstore.png
  app/src/main/res/drawable/ic_home_add_book.xml
  app/src/main/res/drawable/ic_home_book.png
  app/src/main/res/drawable/ic_home_book_background.xml
  app/src/main/res/drawable/ic_home_fisrt_widget.xml
  app/src/main/res/drawable/ic_home_fisrt_widget_right.xml
  app/src/main/res/drawable/ic_home_move_to_timer.xml
  app/src/main/res/drawable/ic_home_search.xml
  app/src/main/res/drawable/ic_home_search_round_box.xml
  app/src/main/res/drawable/ic_home_second_widget.xml
  app/src/main/res/drawable/ic_login_round_box.xml
  app/src/main/res/drawable/img_book.png
  app/src/main/res/drawable/img_book_background.xml
  app/src/main/res/drawable/progressbar_color.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Maro, UI

#15 [UI/#12] 바텀 네비게이션바 수정 타이머 제작
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/bottom_navigation_color.xml
  app/src/main/res/drawable/ic_timer_complete_bg.xml
  app/src/main/res/drawable/ic_timer_round.png
  app/src/main/res/drawable/ic_timer_widget.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_timer.xml
  app/src/main/res/layout/fragment_top.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values/styles.xml
Labels: Maro, UI

#17 [UI/#14] 기록 작성하기 바텀시트 구현
  app/build.gradle.kts
  app/src/main/res/drawable/drawer_corner.xml
  app/src/main/res/drawable/ic_record_save_bg.xml
  app/src/main/res/drawable/img_star_unselected.xml
  app/src/main/res/layout/fragment_record_bottom_sheet.xml
Labels: Simba, UI

#19 [UI/#18] UI전체 맵
  app/src/main/res/drawable/ic_map_search_round_box.xml
  app/src/main/res/layout/fragment_map.xml
Labels: Simba, UI

#21 [UI/#20] 기록 등록하기 -> 장소 검색 UI 구현
  app/build.gradle.kts
  app/src/main/res/drawable/img_map_default.xml
  app/src/main/res/layout/fragment_record_map_search.xml
  app/src/main/res/layout/item_map_search.xml
Labels: Simba, UI

#23 [UI/#22] 독서 맵에서 검색
  app/src/main/res/layout/fragment_map_search.xml
Labels: Simba, UI

#28 [UI/#24] 독서 맵 -> 바텀 시트 구현
  app/src/main/res/drawable/drawer_item_outline.xml
  app/src/main/res/drawable/drawer_little_corner.xml
  app/src/main/res/layout/fragment_map_bottom_sheet.xml
  app/src/main/res/layout/fragment_record_bottom_sheet.xml
  app/src/main/res/layout/fragment_record_map_search.xml
  app/src/main/res/layout/item_map_book_list.xml
  app/src/main/res/layout/item_map_book_record_list.xml
Labels: Simba, FEAT, UI

#30 [UI/#26] 책 상세 페이지 UI 구현
  app/src/main/java/com/example/booking/presentation/search/BookSearchDetailFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchRVA.java
  app/src/main/res/drawable/ic_book_search_detail_save.xml
  app/src/main/res/drawable/img_book_search_detail_cover.png
  app/src/main/res/layout/fragment_book_search_deatil.xml
Labels: Kara, UI

#33 [FEAT/#31] 바텀네비게이션 graph로 설정 완료
  app/build.gradle.kts
  app/src/main/java/com/example/booking/MainActivity.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/main_graph.xml
  gradle/libs.versions.toml
Labels: Simba, FEAT

#39 [Feat/#34] click event1
  app/build.gradle.kts
  app/src/main/java/com/example/booking/MainActivity.java
  app/src/main/java/com/example/booking/data/model/LastReview.java
  app/src/main/java/com/example/booking/presentation/map/MapFragment.java
  app/src/main/java/com/example/booking/presentation/map/MapSearchFragment.java
  app/src/main/java/com/example/booking/presentation/registration/RecordRegistrationBottomSheetDialogFragment.java
  app/src/main/java/com/example/booking/presentation/registration/RecordRegistrationFragment.java
  app/src/main/java/com/example/booking/presentation/registration/RecordRegistrationMapSearchFragment.java
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_map_search.xml
  app/src/main/res/layout/fragment_record_registration.xml
  app/src/main/res/layout/fragment_record_registration_map_search.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/styles.xml
Labels: Simba, FEAT

#41 [Feat/#32] click event2
  app/src/main/java/com/example/booking/presentation/record/RecordFragment.java
  app/src/main/java/com/example/booking/presentation/record/RecordSpecificFragment.java
  app/src/main/java/com/example/booking/presentation/record/TimerFragment.java
  app/src/main/res/drawable/ic_timer_x.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/fragment_record_specific.xml
  app/src/main/res/layout/fragment_timer.xml
  app/src/main/res/navigation/main_graph.xml
Labels: Maro, FEAT, FIX

#35 [UI/#27] 책 저장 바텀 시트 UI 구현
  app/src/main/java/com/example/booking/presentation/search/BookSearchDetailFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchSaveBottomSheetFragment.java
  app/src/main/res/color/text_color_selector.xml
  app/src/main/res/drawable/button_backgroung_selector.xml
  app/src/main/res/drawable/img_book_search_save_bg.png
  app/src/main/res/drawable/img_book_search_save_type_non_sel.png
  app/src/main/res/drawable/img_book_search_save_type_sel.png
  app/src/main/res/layout/fragment_book_search_save_bottom_sheet.xml
  app/src/main/res/values/colors.xml
Labels: Kara, UI

#44 [UI/#37] 프로필 수정 UI 구현
  app/src/main/java/com/example/booking/presentation/mypage/MyProfileChangeFragment.java
  app/src/main/res/drawable/ic_my_page_profile_change_icon.xml
  app/src/main/res/drawable/ic_my_page_profile_change_nick_name_check.xml
  app/src/main/res/drawable/img_mypage_nick_name_change.png
  app/src/main/res/layout/fragment_my_profile_change.xml
Labels: Kara, UI

#49 [Feat/#46] 책 검색 click event 기능 구현
  app/src/main/java/com/example/booking/presentation/home/HomeFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchDetailFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchSaveBottomSheetFragment.java
  app/src/main/res/navigation/main_graph.xml
Labels: Kara, FEAT

#51 [Mod/#50] my page navigation 탭 제거
  app/src/main/java/com/example/booking/presentation/mypage/MyPersonalInfoFragment.java
  app/src/main/java/com/example/booking/presentation/mypage/MyProfileChangeFragment.java
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/main_graph.xml
Labels: Kara, MOD

#52 [UI/#48] 검색 페이지 UI 수정
  app/src/main/java/com/example/booking/presentation/search/BookSearchSaveBottomSheetFragment.java
  app/src/main/res/drawable/ic_book_search_detail_save.xml
  app/src/main/res/drawable/ic_book_search_filter_bg.xml
  app/src/main/res/drawable/ic_item_book_search_bg.xml
  app/src/main/res/layout/fragment_book_search.xml
  app/src/main/res/layout/fragment_book_search_deatil.xml
  app/src/main/res/layout/item_book_search.xml
Labels: Kara, UI

#55 [FEAT/#53] 프로필 사진 수정 기능 구현
  app/src/main/java/com/example/booking/presentation/mypage/MyProfileChangeFragment.java
  app/src/main/res/layout/fragment_my_profile_change.xml
Labels: Kara, FEAT

#54 [UI/#40] UI 수정 및 클릭 이벤트 마무리
  app/src/main/java/com/example/booking/presentation/registration/RecordRegistrationBottomSheetDialogFragment.java
  app/src/main/java/com/example/booking/presentation/registration/RecordRegistrationFragment.java
  app/src/main/java/com/example/booking/presentation/registration/RecordRegistrationMapSearchFragment.java
  app/src/main/res/drawable/drawer_little_corenr_outline.xml
  app/src/main/res/layout/fragment_map_bottom_sheet.xml
  app/src/main/res/layout/fragment_map_search.xml
  app/src/main/res/layout/fragment_record_bottom_sheet.xml
  app/src/main/res/layout/fragment_record_registration.xml
  app/src/main/res/navigation/main_graph.xml
Labels: Simba, FEAT, UI, FIX

#56 [Feat/#42] click event3
  app/src/main/java/com/example/booking/presentation/home/HomeFragment.java
  app/src/main/java/com/example/booking/presentation/record/RecordFragment.java
  app/src/main/java/com/example/booking/presentation/record/RecordSpecificFragment.java
  app/src/main/java/com/example/booking/presentation/record/TimerFragment.java
  app/src/main/java/com/example/booking/presentation/record/adapter/BookAdapter.java
  app/src/main/java/com/example/booking/presentation/registration/RecordRegistrationBottomSheetDialogFragment.java
  app/src/main/res/drawable/ic_timer_x.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/fragment_record_list_item.xml
  app/src/main/res/layout/fragment_record_specific.xml
  app/src/main/res/layout/fragment_timer.xml
  app/src/main/res/navigation/main_graph.xml
Labels: Maro, FEAT

#57 [Fix] home fragment error fix
  app/src/main/java/com/example/booking/presentation/home/HomeFragment.java
Labels: Maro, FIX

#60 [FIX/#40]
  .idea/misc.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_map_search.xml
  app/src/main/res/layout/fragment_record_registration.xml
  app/src/main/res/layout/fragment_record_registration_map_search.xml
Labels: Simba, FIX

#61 [Fix/59] navigation 수정
  app/src/main/res/layout/fragment_record_specific.xml
  app/src/main/res/layout/fragment_timer.xml
  app/src/main/res/navigation/main_graph.xml
Labels: Maro, FIX

#65 [UI/#62] UI 작업 완료
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/booking/presentation/home/HomeFragment.java
  app/src/main/res/drawable/ic_home_first_widget_right_bg_outline.xml
  app/src/main/res/drawable/ic_home_second_widget.xml
  app/src/main/res/layout/fragment_book_search.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/layout/fragment_record_registration.xml
  app/src/main/res/layout/fragment_record_specific.xml
Labels: :zap:Maro, UI

#67 [Feat/#66] 로그인 api 구현
  app/build.gradle.kts
  app/google-services.json
  app/src/main/java/com/example/booking/presentation/LoginActivity.java
  app/src/main/java/com/example/booking/presentation/SignupFragment.java
  app/src/main/res/drawable/ic_google_login.png
  app/src/main/res/drawable/ic_google_logo.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: :zap:Maro, FEAT

#69 [FEAT/#64] 도서 검색 api 연동 준비
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/booking/BookingApplication.java
  app/src/main/java/com/example/booking/MainActivity.java
  app/src/main/java/com/example/booking/datasource/NaverDataSource.java
  app/src/main/java/com/example/booking/datasourceImpl/NaverDataSourceImpl.java
  app/src/main/java/com/example/booking/di/DataSourceModule.java
  app/src/main/java/com/example/booking/di/NetworkModule.java
  app/src/main/java/com/example/booking/dto/response/BookSearchResponseDto.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchRVA.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchViewModel.java
  app/src/main/java/com/example/booking/repository/BookRepository.java
  app/src/main/java/com/example/booking/service/NaverApiService.java
  build.gradle.kts
Labels: :zap: Kara, FEAT

#71 Feat/#68 firebase db 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/booking/data/model/Record.java
  app/src/main/java/com/example/booking/di/NetworkModule.java
  app/src/main/java/com/example/booking/dto/response/BookSearchResponseDto.java
  app/src/main/java/com/example/booking/presentation/LoginActivity.java
  app/src/main/java/com/example/booking/presentation/record/RecordFragment.java
  app/src/main/java/com/example/booking/presentation/record/RecordSpecificFragment.java
  app/src/main/java/com/example/booking/presentation/record/TimerFragment.java
  app/src/main/java/com/example/booking/presentation/record/adapter/BookAdapter.java
  app/src/main/java/com/example/booking/presentation/registration/RecordRegistrationFragment.java
  app/src/main/java/com/example/booking/presentation/registration/RecordRegistrationViewModel.java
  app/src/main/res/drawable/ic_booking_logo.xml
  app/src/main/res/drawable/ic_booking_logo_txt.xml
  app/src/main/res/drawable/splash.xml
  app/src/main/res/drawable/splash_branding_txt.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/fragment_record_specific.xml
  app/src/main/res/layout/fragment_record_specific_list_item.xml
  app/src/main/res/layout/fragment_timer.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: :zap:Maro, FEAT

#73 Feat/#72 member db 구현 로그아웃
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/example/booking/BookingApplication.java
  app/src/main/java/com/example/booking/MainActivity.java
  app/src/main/java/com/example/booking/dto/response/BookSearchResponseDto.java
  app/src/main/java/com/example/booking/presentation/LoginActivity.java
  app/src/main/java/com/example/booking/presentation/SignupFragment.java
  app/src/main/java/com/example/booking/presentation/home/HomeFragment.java
  app/src/main/java/com/example/booking/presentation/mypage/MyFragment.java
  app/src/main/java/com/example/booking/presentation/mypage/MyProfileChangeFragment.java
  app/src/main/java/com/example/booking/presentation/record/RecordFragment.java
  app/src/main/java/com/example/booking/presentation/record/RecordSpecificFragment.java
  app/src/main/java/com/example/booking/presentation/record/adapter/BookAdapter.java
  app/src/main/java/com/example/booking/presentation/record/adapter/RecordAdapter.java
  app/src/main/res/drawable/drawer_little_corenr_outline.xml
  app/src/main/res/layout/activity_login.xml
  gradle/libs.versions.toml
Labels: :zap:Maro, FEAT

#75 [FEAT/#70] 책 검색 화면 간 데이터 전달
  app/build.gradle.kts
  app/src/main/java/com/example/booking/dto/response/BookSearchResponseDto.java
  app/src/main/java/com/example/booking/presentation/search/Book.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchDetailFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchRVA.java
  app/src/main/res/layout/fragment_book_search.xml
  app/src/main/res/layout/fragment_book_search_deatil.xml
  app/src/main/res/layout/item_book_search.xml
  app/src/main/res/navigation/main_graph.xml
  build.gradle.kts
Labels: :zap: Kara, FEAT

#78 [Feat/maro] 수민 담당 DB, 기능 구현 완료
  app/src/main/java/com/example/booking/data/model/Record.java
  app/src/main/java/com/example/booking/presentation/home/HomeFragment.java
  app/src/main/java/com/example/booking/presentation/record/RecordFragment.java
  app/src/main/java/com/example/booking/presentation/record/RecordSpecificFragment.java
  app/src/main/java/com/example/booking/presentation/record/TimerFragment.java
  app/src/main/java/com/example/booking/presentation/record/adapter/RecordAdapter.java
  app/src/main/res/drawable/ic_home_d_day_bg.xml
  app/src/main/res/drawable/ic_home_fisrt_widget.xml
  app/src/main/res/drawable/ic_home_fisrt_widget_right.xml
  app/src/main/res/drawable/ic_home_total_time_bg.xml
  app/src/main/res/drawable/ic_record_specific_list_item_memo.xml
  app/src/main/res/drawable/ic_record_specific_list_item_memo_clicked.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/fragment_record_specific.xml
  app/src/main/res/layout/fragment_record_specific_list_item.xml
Labels: :zap:Maro, FEAT

#81 [FEAT/#76] firebase 도서 추가하기 기능 구현
  app/src/main/java/com/example/booking/presentation/mypage/MyFragment.java
  app/src/main/java/com/example/booking/presentation/mypage/MyProfileChangeFragment.java
  app/src/main/java/com/example/booking/presentation/mypage/MyProfileChangeViewModel.java
  app/src/main/java/com/example/booking/presentation/mypage/MyViewModel.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchDetailFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchDetailViewModel.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchSaveBottomSheetFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchViewModel.java
  app/src/main/res/drawable/img_my_default.png
  app/src/main/res/drawable/img_star_filled.xml
  app/src/main/res/drawable/img_star_unfilled.xml
  app/src/main/res/layout/fragment_book_search_save_bottom_sheet.xml
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/navigation/main_graph.xml
Labels: :zap: Kara, FEAT

#84 [FIX/#82] firebase timestamp 오류 해결
  app/src/main/java/com/example/booking/presentation/search/BookSearchDetailFragment.java
  app/src/main/java/com/example/booking/presentation/search/BookSearchSaveBottomSheetFragment.java
Labels: :zap: Kara, FIX

#83 Feat/#80 내가 등록한 장소 마커 표시하기
  app/src/main/java/com/example/booking/adapter/MapSearchAdapter.java
  app/src/main/java/com/example/booking/presentation/map/MapBottomSheetDialogFragment.java
  app/src/main/java/com/example/booking/presentation/map/MapFragment.java
  app/src/main/java/com/example/booking/presentation/map/MapPlaceAdapter.java
  app/src/main/java/com/example/booking/presentation/map/MapSearchFragment.java
  app/src/main/java/com/example/booking/presentation/map/Place.java
  app/src/main/java/com/example/booking/presentation/registration/PlaceSearchKeyword.java
  app/src/main/java/com/example/booking/presentation/registration/RecordRegistrationFragment.java
  app/src/main/java/com/example/booking/presentation/registration/RecordRegistrationMapSearchFragment.java
  app/src/main/res/drawable/custommarker.png
  app/src/main/res/drawable/ic_bottom_map.xml
  app/src/main/res/drawable/ic_custom_marker.xml
  app/src/main/res/layout/fragment_map_search.xml
  app/src/main/res/layout/item_map_book_list.xml
Labels: :zap:Simba, FEAT
